required:
  - stickySession
  - balance
  - xForwardedFor
  - idleTimeOut
description: Different configuration assigned for the load balancer
title: loadBalancerConfiguration
type: object
nullable: true
properties:
  stickySession:
    $ref: ./stickySession.yaml
  balance:
    $ref: ./balance.yaml
  xForwardedFor:
    type: boolean
    description: Is xForwardedFor header enabled or not
  idleTimeOut:
    type: integer
    description: Time to close the connection if load balancer is idle
