get:
  operationId: >-
    get/colocations/{colocationId}/notificationSettings/datatraffic/{notificationId}
  summary: Inspect datatraffic notification settings
  description: ''
  parameters:
    - $ref: ../components/parameters/limit.yaml
    - $ref: ../components/parameters/offset.yaml
  responses:
    '200':
      description: ''
      content:
        application/json:
          schema:
            type: object
            $schema: http://json-schema.org/draft-04/schema
            id: http://jsonschema.net
            properties:
              actions:
                description: An array of notification setting actions
                items:
                  properties:
                    lastTriggeredAt:
                      description: >-
                        Date timestamp when the last notification email
                        triggered
                      type: string
                    type:
                      description: Type of action
                      enum:
                        - EMAIL
                      type: string
                  type: object
                type: array
              frequency:
                type: string
                description: Frequency
                enum:
                  - DAILY
                  - WEEKLY
                  - MONTHLY
              id:
                type: string
                description: Identifier of the notification setting
              lastCheckedAt:
                description: >-
                  Date timestamp when the system last checked the colocation for
                  threshold limit
                type: string
              threshold:
                description: Threshold Value
                type: string
              thresholdExceededAt:
                description: Date timestamp when the threshold exceeded the limit
                type: string
              unit:
                type: string
                description: Unit
                enum:
                  - MB
                  - GB
                  - TB
          examples:
            example:
              value:
                actions:
                  - lastTriggeredAt: '2021-03-16T01:01:44+00:00'
                    type: EMAIL
                frequency: WEEKLY
                id: '12345'
                lastCheckedAt: '2021-03-16T01:01:41+00:00'
                threshold: '1'
                thresholdExceededAt: '2021-03-16T01:01:41+00:00'
                unit: GB
    '401':
      description: Authentication is required.
      content: {}
    '403':
      description: ''
      content:
        application/json:
          examples:
            example:
              value:
                errorCode: ACCESS_DENIED
                errorMessage: The access token is expired or invalid.
    '404':
      description: ''
      content:
        application/json:
          examples:
            example:
              value:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: '404'
                errorMessage: Resource not found
  tags:
    - Colocations
  x-codeSamples:
    - lang: Shell + Curl
      source:
        $ref: >-
          ../code_samples/Shell+Curl/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/getundefined
    - lang: Python + Python3
      source:
        $ref: >-
          ../code_samples/Python+Python3/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/getundefined
    - lang: Php + Http2
      source:
        $ref: >-
          ../code_samples/Php+Http2/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/getundefined
    - lang: Javascript + Jquery
      source:
        $ref: >-
          ../code_samples/Javascript+Jquery/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/getundefined
    - lang: Go + Native
      source:
        $ref: >-
          ../code_samples/Go+Native/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/getundefined
put:
  operationId: >-
    put/colocations/{colocationId}/notificationSettings/datatraffic/{notificationId}
  summary: Update datatraffic notification settings
  description: ''
  requestBody:
    content:
      application/json:
        examples:
          example:
            value:
              frequency: DAILY
              unit: GB
              threshold: '1'
        schema:
          type: object
          $schema: http://json-schema.org/draft-04/schema
          id: http://jsonschema.net
          properties:
            frequency:
              type: string
              description: Frequency for the Datatraffic Notification
              enum:
                - DAILY
                - WEEKLY
                - MONTHLY
              examples:
                - DAILY
            unit:
              type: string
              description: Unit for the Datatraffic Notification
              enum:
                - MB
                - GB
                - TB
              examples:
                - GB
            threshold:
              type: string
              description: Threshold Value for the Datatraffic Notification
              examples:
                - '10'
          required:
            - frequency
            - unit
            - threshold
  responses:
    '200':
      description: ''
      content:
        application/json:
          schema:
            type: object
            $schema: http://json-schema.org/draft-04/schema
            id: http://jsonschema.net
            properties:
              actions:
                description: An array of notification setting actions
                items:
                  properties:
                    lastTriggeredAt:
                      description: >-
                        Date timestamp when the last notification email
                        triggered
                      type: string
                    type:
                      description: Type of action
                      enum:
                        - EMAIL
                      type: string
                  type: object
                type: array
              frequency:
                type: string
                description: Frequency
                enum:
                  - DAILY
                  - WEEKLY
                  - MONTHLY
              id:
                type: string
                description: Identifier of the notification setting
              lastCheckedAt:
                description: >-
                  Date timestamp when the system last checked the colocation for
                  threshold limit
                type: string
              threshold:
                description: Threshold Value
                type: string
              thresholdExceededAt:
                description: Date timestamp when the threshold exceeded the limit
                type: string
              unit:
                type: string
                description: Unit
                enum:
                  - MB
                  - GB
                  - TB
          examples:
            example:
              value:
                actions:
                  - lastTriggeredAt: '2021-03-16T01:01:44+00:00'
                    type: EMAIL
                frequency: WEEKLY
                id: '12345'
                lastCheckedAt: '2021-03-16T01:01:41+00:00'
                threshold: '1'
                thresholdExceededAt: '2021-03-16T01:01:41+00:00'
                unit: GB
    '401':
      description: Authentication is required.
      content: {}
    '403':
      description: ''
      content:
        application/json:
          examples:
            example:
              value:
                errorCode: ACCESS_DENIED
                errorMessage: The access token is expired or invalid.
  tags:
    - Colocations
  x-codeSamples:
    - lang: Shell + Curl
      source:
        $ref: >-
          ../code_samples/Shell+Curl/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/putundefined
    - lang: Python + Python3
      source:
        $ref: >-
          ../code_samples/Python+Python3/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/putundefined
    - lang: Php + Http2
      source:
        $ref: >-
          ../code_samples/Php+Http2/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/putundefined
    - lang: Javascript + Jquery
      source:
        $ref: >-
          ../code_samples/Javascript+Jquery/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/putundefined
    - lang: Go + Native
      source:
        $ref: >-
          ../code_samples/Go+Native/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/putundefined
delete:
  operationId: >-
    delete/colocations/{colocationId}/notificationSettings/datatraffic/{notificationId}
  summary: Delete datatraffic notification settings
  description: ''
  responses:
    '204':
      description: No Content
      content: {}
    '401':
      description: Authentication is required.
      content: {}
    '403':
      description: ''
      content:
        application/json:
          examples:
            example:
              value:
                errorCode: ACCESS_DENIED
                errorMessage: The access token is expired or invalid.
  tags:
    - Colocations
  x-codeSamples:
    - lang: Shell + Curl
      source:
        $ref: >-
          ../code_samples/Shell+Curl/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/deleteundefined
    - lang: Python + Python3
      source:
        $ref: >-
          ../code_samples/Python+Python3/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/deleteundefined
    - lang: Php + Http2
      source:
        $ref: >-
          ../code_samples/Php+Http2/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/deleteundefined
    - lang: Javascript + Jquery
      source:
        $ref: >-
          ../code_samples/Javascript+Jquery/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/deleteundefined
    - lang: Go + Native
      source:
        $ref: >-
          ../code_samples/Go+Native/bareMetals_v2_colocations_{colocationId}_notificationSettings_datatraffic_{notificationId}/deleteundefined
parameters:
  - schema:
      type: string
    name: notificationId
    in: path
    required: true
  - $ref: ../components/parameters/colocationId.yaml
