get:
  description: List all datatraffic notification settings for this server.
  operationId: getDataTrafficNotificationSettingList
  parameters:
    - $ref: ../components/parameters/limit.yaml
    - $ref: ../components/parameters/offset.yaml
  responses:
    '200':
      content:
        application/json:
          example:
            _metadata:
              limit: 10
              offset: 0
              totalCount: 2
            datatrafficNotificationSettings:
              - id: '64371'
                frequency: DAILY
                threshold: '25000'
                unit: MB
                lastCheckedAt: null
                thresholdExceededAt: null
                actions:
                  - type: EMAIL
                    lastTriggeredAt: null
              - id: '64372'
                frequency: MONTHLY
                threshold: '10000000'
                unit: MB
                lastCheckedAt: null
                thresholdExceededAt: null
                actions:
                  - type: EMAIL
                    lastTriggeredAt: null
          schema:
            $ref: >-
              ../components/schemas/getDataTrafficNotificationSettingListResult.yaml
      description: Ok.
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/403.yaml
  summary: List data traffic notification settings
  tags:
    - Notification Settings
    - Dedicated Servers
  x-codeSamples:
    - lang: Shell + Curl
      source:
        $ref: >-
          ../code_samples/Shell+Curl/bareMetals_v2_servers_{serverId}_notificationSettings_datatraffic/getundefined
    - lang: Python + Python3
      source:
        $ref: >-
          ../code_samples/Python+Python3/bareMetals_v2_servers_{serverId}_notificationSettings_datatraffic/getundefined
    - lang: Php + Http2
      source:
        $ref: >-
          ../code_samples/Php+Http2/bareMetals_v2_servers_{serverId}_notificationSettings_datatraffic/getundefined
    - lang: Javascript + Jquery
      source:
        $ref: >-
          ../code_samples/Javascript+Jquery/bareMetals_v2_servers_{serverId}_notificationSettings_datatraffic/getundefined
    - lang: Go + Native
      source:
        $ref: >-
          ../code_samples/Go+Native/bareMetals_v2_servers_{serverId}_notificationSettings_datatraffic/getundefined
parameters:
  - $ref: ../components/parameters/serverId.yaml
post:
  description: Create a new data traffic notification setting for this server.
  operationId: createDataTrafficNotificationSetting
  requestBody:
    content:
      application/json:
        example:
          frequency: DAILY
          threshold: '1'
          unit: MB
        schema:
          $ref: ../components/schemas/dataTrafficNotificationSettingOpts.yaml
  responses:
    '201':
      content:
        application/json:
          example:
            actions:
              - lastTriggeredAt: '2021-03-16T01:01:44+00:00'
                type: EMAIL
            frequency: WEEKLY
            id: '12345'
            lastCheckedAt: '2021-03-16T01:01:41+00:00'
            threshold: '1'
            thresholdExceededAt: '2021-03-16T01:01:41+00:00'
            unit: GB
          schema:
            $ref: ../components/schemas/dataTrafficNotificationSetting.yaml
      description: Created.
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/403.yaml
  summary: Create a data traffic notification setting
  tags:
    - Notification Settings
    - Dedicated Servers
  x-codeSamples:
    - lang: Shell + Curl
      source:
        $ref: >-
          ../code_samples/Shell+Curl/bareMetals_v2_servers_{serverId}_notificationSettings_datatraffic/postundefined
    - lang: Python + Python3
      source:
        $ref: >-
          ../code_samples/Python+Python3/bareMetals_v2_servers_{serverId}_notificationSettings_datatraffic/postundefined
    - lang: Php + Http2
      source:
        $ref: >-
          ../code_samples/Php+Http2/bareMetals_v2_servers_{serverId}_notificationSettings_datatraffic/postundefined
    - lang: Javascript + Jquery
      source:
        $ref: >-
          ../code_samples/Javascript+Jquery/bareMetals_v2_servers_{serverId}_notificationSettings_datatraffic/postundefined
    - lang: Go + Native
      source:
        $ref: >-
          ../code_samples/Go+Native/bareMetals_v2_servers_{serverId}_notificationSettings_datatraffic/postundefined
