openapi: 3.0.0
info:
  description: >-
    This document outlines the ordering API. The API is only available for
    customers with invoice payment method.
  title: Ordering
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    altText: Leaseweb developer documentation
    backgroundColor: '#5484c6'
    href: https://developer.leaseweb.com
    url: https://developer.leaseweb.com/images/logo.png
servers:
  - url: https://api.leaseweb.com
security:
  - X-LSW-Auth: []
tags:
  - name: Servers
paths:
  /ordering/v1/products/dedicatedServers:
    $ref: paths/ordering_v1_products_dedicatedServers.yaml
  /ordering/v1/products/dedicatedServers/{dedicatedServerId}:
    $ref: paths/ordering_v1_products_dedicatedServers_{dedicatedServerId}.yaml
  /ordering/v1/products/dedicatedServers/{dedicatedServerId}/order:
    $ref: paths/ordering_v1_products_dedicatedServers_{dedicatedServerId}_order.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    X-LSW-Auth:
      name: X-LSW-Auth
      type: apiKey
      in: header
      description: API key authentication by setting `X-LSW-Auth` header.
