properties:
  type:
    type: string
    enum:
      - INVALIDATION
      - CREATE_DIST
      - UPDATE_DIST
      - DELETE_DIST
  status:
    type: string
    enum:
      - PENDING
      - IN_PROGRESS
      - FINISHED
      - ERROR
  id:
    type: string
  customerId:
    type: string
  created:
    type: string
    format: date-time
  updated:
    anyOf:
      - type: string
        format: date-time
      - type: 'null'
  resource:
    title: resource
    type: object
    additionalProperties: true
required:
  - type
  - status
  - id
  - customerId
  - created
  - resource
type: object
