parameters:
  - $ref: ../components/parameters/vpsId.yaml
get:
  operationId: getNotificationSettingList
  parameters:
    - $ref: ../components/parameters/limit.yaml
    - $ref: ../components/parameters/offset.yaml
  responses:
    '200':
      description: OK.
      content:
        application/json:
          example:
            _metadata:
              totalCount: 2
              limit: 10
              offset: 0
            notificationSettings:
              - id: ff6bbd04-c24c-4ecf-b09d-e6c415a65d63
                threshold:
                  unit: GB
                  value: 2000
                type: DATA_TRAFFIC
                timePeriod: DAY
                action: POWER_OFF
                channels:
                  - type: EMAIL
                    contactGroup: TECHNICAL
                    contacts:
                      - john.doe@example.com
              - id: cc6bbd04-c24c-4ecf-b09d-e6c415a65d78
                threshold:
                  unit: GB
                  value: 1000
                type: DATA_TRAFFIC
                timePeriod: DAY
                action: null
                channels:
                  - type: EMAIL
                    contactGroup: TECHNICAL
                    contacts:
                      - jim.doe@example.com
          schema:
            $ref: ../components/schemas/getNotificationSettingListResult.yaml
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/503.yaml
  summary: List the notification settings of a customer
  tags:
    - VPS
  x-codeSamples:
    - lang: Shell + Curl
      source:
        $ref: >-
          ../code_samples/Shell+Curl/publicCloud_v1_vps_vps_{vpsId}_notificationSettings_dataTraffic/getundefined
    - lang: Python + Python3
      source:
        $ref: >-
          ../code_samples/Python+Python3/publicCloud_v1_vps_vps_{vpsId}_notificationSettings_dataTraffic/getundefined
    - lang: Php + Http2
      source:
        $ref: >-
          ../code_samples/Php+Http2/publicCloud_v1_vps_vps_{vpsId}_notificationSettings_dataTraffic/getundefined
    - lang: Javascript + Jquery
      source:
        $ref: >-
          ../code_samples/Javascript+Jquery/publicCloud_v1_vps_vps_{vpsId}_notificationSettings_dataTraffic/getundefined
    - lang: Go + Native
      source:
        $ref: >-
          ../code_samples/Go+Native/publicCloud_v1_vps_vps_{vpsId}_notificationSettings_dataTraffic/getundefined
